# Generated by Django 4.2.16 on 2024-10-13 06:37

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('category', models.CharField(choices=[('Environment', 'Environment'), ('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Life-style', 'Life-style'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Education', 'Education'), ('DIY', 'DIY'), ('News', 'News'), ('Travel', 'Travel'), ('Case-Studies', 'Case-Studies'), ('Others', 'Others')], default=('Others', 'Others'), max_length=20)),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('meta_description', models.CharField(default='description', max_length=300)),
                ('author', models.CharField(choices=[('Shreyash', 'Shreyash'), ('Tanmay', 'Tanmay'), ('Prathmesh', 'Prathmesh')], default=('Shreyash', 'Shreyash'), max_length=10)),
                ('sponsered', models.BooleanField(default=False)),
                ('show_blog_at', models.CharField(choices=[('None', 'None'), ('Main', 'Main'), ('Side', 'Side')], default=('None', 'None'), max_length=20)),
                ('published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
