# Generated by Django 4.2.14 on 2024-07-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'technology'), ('soft', 'software'), ('renew', 'renewable'), ('recycle', 'recyclable'), ('recent', 'recent')], default=('recent', 'recent'), max_length=20)),
                ('blog_date', models.DateTimeField()),
            ],
        ),
    ]
