# Generated by Django 4.2.16 on 2025-02-28 16:08

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('page_title', models.CharField(blank=True, max_length=60, null=True)),
                ('Title', models.CharField(max_length=100)),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, quality=80, scale=None, size=[950, 300], upload_to='')),
                ('table_of_content', models.BooleanField(default=False)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('category', models.CharField(choices=[('Environment', 'Environment'), ('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Life-style', 'Life-style'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Education', 'Education'), ('DIY', 'DIY'), ('News', 'News'), ('Travel', 'Travel'), ('Case-Studies', 'Case-Studies'), ('Others', 'Others')], default=('Others', 'Others'), max_length=20)),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(default='description', max_length=300)),
                ('sponsored', models.BooleanField(default=False)),
                ('nofollow', models.BooleanField(default=False)),
                ('dofollow', models.BooleanField(default=False)),
                ('noreferrer', models.BooleanField(default=False)),
                ('noopener', models.BooleanField(default=False)),
                ('show_blog_at', models.CharField(choices=[('None', 'None'), ('Main', 'Main'), ('Side', 'Side')], default=('None', 'None'), max_length=20)),
                ('published', models.BooleanField(default=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BotIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('suggestion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_views', to='blogs.blog')),
            ],
        ),
    ]
