# Generated by Django 4.2.16 on 2025-03-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blog_page_title_blog_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='queued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='revert',
            field=models.BooleanField(default=True),
        ),
    ]
