# Generated by Django 4.2.16 on 2024-10-14 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
