# Generated by Django 4.2.16 on 2025-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blog_queued_blog_revert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='revert',
            field=models.BooleanField(default=False),
        ),
    ]
