# Generated by Django 4.2.16 on 2025-03-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blog_revert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='revert',
        ),
    ]
