# Generated by Django 4.2.14 on 2024-08-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_registration_subscribe_alter_blog_blog_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='subscribe',
            name='name',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
