# Generated by Django 4.2.16 on 2024-10-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
