# Generated by Django 4.2.16 on 2024-10-16 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blog_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='alt_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
