# Generated by Django 4.2.15 on 2024-08-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_delete_registration_subscribe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("Environment", "Environment"),
                    ("Technology", "Technology"),
                    ("Agriculture", "Agriculture"),
                    ("Life-style", "Life-style"),
                    ("Fashion", "Fashion"),
                    ("Food", "Food"),
                    ("Education", "Education"),
                    ("DIY", "DIY"),
                    ("News", "News"),
                    ("Travel", "Travel"),
                    ("Case Studies", "Case Studies"),
                ],
                default=("recent", "recent"),
                max_length=20,
            ),
        ),
    ]
