# Generated by Django 4.2.16 on 2024-10-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_blog_alt_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='alt_text',
        ),
    ]
