# Generated by Django 4.2.16 on 2024-11-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_remove_blog_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='page_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
