# Generated by Django 4.2.15 on 2024-08-08 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0008_blog_keywords_blog_meta_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="category",
            field=models.CharField(
                choices=[
                    ("Environment", "Environment"),
                    ("Technology", "Technology"),
                    ("Agriculture", "Agriculture"),
                    ("Life-style", "Life-style"),
                    ("Fashion", "Fashion"),
                    ("Food", "Food"),
                    ("Education", "Education"),
                    ("DIY", "DIY"),
                    ("News", "News"),
                    ("Travel", "Travel"),
                    ("Case-Studies", "Case-Studies"),
                    ("Others", "Others"),
                ],
                default=("Others", "Others"),
                max_length=20,
            ),
        ),
    ]
