# Generated by Django 4.2.20 on 2025-10-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_read_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
