# Generated by Django 4.2.16 on 2024-11-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    def backfill_updated_at(apps, schema_editor):
        BlogPost = apps.get_model('blogs', 'Blog')
        for post in BlogPost.objects.all():
            post.updated_at = post.blog_date # Or another meaningful timestamp
            post.save()

    dependencies = [
        ('blogs', '0009_blog_updated_at'),
    ]

    operations = [
        migrations.RunPython(backfill_updated_at),
    ]
