# Generated by Django 4.2.20 on 2025-10-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_blog_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestions',
            name='topic',
            field=models.CharField(choices=[('Feedback', 'General Feedback'), ('Blog Idea', 'Blog Idea'), ('Collaboration', 'Collaboration Proposal')], default='Feedback', max_length=50),
        ),
    ]
