# Generated by Django 4.2.15 on 2024-08-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0010_blog_author_blog_show_blog_at_blog_sponsered"),
    ]

    operations = [
        migrations.CreateModel(
            name="service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
