# Generated by Django 4.2.20 on 2025-10-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_suggestions_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Environment', 'Environment'), ('Technology', 'Technology'), ('Agriculture', 'Agriculture'), ('Life-style', 'Life-style'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Education', 'Education'), ('DIY', 'DIY'), ('News', 'News'), ('Travel', 'Travel'), ('Case-Studies', 'Case-Studies'), ('Others', 'Others')], db_index=True, default=('Others', 'Others'), max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='show_blog_at',
            field=models.CharField(choices=[('None', 'None'), ('Main', 'Main'), ('Side', 'Side')], db_index=True, default=('None', 'None'), max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sponsored',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogview',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='blogview',
            unique_together={('blog', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['published', '-blog_date'], name='blogs_blog_publish_c25e14_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['category', 'published'], name='blogs_blog_categor_ebf608_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['sponsored', 'show_blog_at', 'published'], name='blogs_blog_sponsor_cbb3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['blog', 'ip_address'], name='blogs_blogv_blog_id_b9a600_idx'),
        ),
    ]
