# Generated by Django 4.2.15 on 2024-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0011_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="suggestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("suggestion", models.TextField()),
            ],
        ),
    ]
