# Generated by Django 4.2.16 on 2024-12-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_blog_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='nofollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='noopener',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='noreferrer',
            field=models.BooleanField(default=False),
        ),
    ]
