# Generated by Django 4.2.16 on 2025-02-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_blogview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='sponsered',
            new_name='sponsored',
        ),
    ]
