# Generated by Django 4.2.16 on 2025-02-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_rename_sponsered_blog_sponsored'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
