# Generated by Django 4.2.16 on 2025-02-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20250224_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
    ]
