# Generated by Django 4.2.16 on 2025-02-26 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_remove_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_user',
        ),
    ]
